### ISSUE TITLE
Compilation fails with newest build tools

### ISSUE THREAD

**Issue by mamciek** [indeyets/syck#10]
With recent updates to the packages gcc, glibc, etc the project cannot be compiled.  See attached build log with error.

https://gist.github.com/3169285

Build environment:
Arch Linux
Kernel: Linux 3.4.6-1-ARCH #1 SMP PREEMPT Fri Jul 20 08:21:26 CEST 2012 x86_64 GNU/Linux
gcc: 4.7.1
bison: 2.6
flex: 2.5.36
automake: 1.12.2
autoconf: 2.69
m4: 1.4.16
make: 3.82
glibc: 2.16.0

**Comment by fedya** [comment]
Any fix?

**Comment by indeyets** [comment]
I don't have access to system with gcc-4.7 at the moment.

it builds fine on ubuntu 12.04 with gcc-4.6 and on OS X with gcc-4.2 and clang-4.0

patches are welcome, if you can figure it out on your own :)

**Comment by mamciek** [comment]
I belive the problem exists in gram.y file, but unfortunately I have no experiece with bison at all, so I can't figure out how to solve it

**Comment by xhochy** [comment]
YYPARSE_PARAM and YYLEX_PARAM were deprecated with bison 2.6

http://savannah.gnu.org/forum/forum.php?forum_id=7305

**Comment by indeyets** [comment]
@mamciek @fedya can you check that this commit fixes issue?

**Comment by mamciek** [comment]
Yes, it does - the compilation completes now
