### ISSUE TITLE
PATCH: ext/cocoa: automatic building of libsyck.a for currently active architectures)

### ISSUE THREAD

**Issue by rsms** [indeyets/syck#2]
This patch...
- Enables building YAML.framework as a universal binary
- Automatically builds libsyck for active architectures, but only when needed
- Removes the requirement to install libsyck system-wide (links with explicitly built libsyck.a)

https://gist.github.com/raw/731929/0001-Enabled-automatic-building-of-regular-or-universal-l.patch

**Comment by rsms** [comment]
Note: This applies on top of master@ 42db5811c5eaaeb5fd224c94d3667c7169689de5 (current master as of writing this)

**Comment by indeyets** [comment]
applied
