### ISSUE TITLE
macports support

### ISSUE THREAD

**Issue by apinstein** [indeyets/syck#4]
Thanks for taking over the project. I am using Macports to compile syck on Mac OS X and updated the portfile to use your project.

Right now I've got it pointing to the 0.70 "download". Are you interested in having me add an official Portfile to the project so we can keep the Macports community up-to-speed with the latest Syck?

LMK I am glad to contribute.

Alan

**Comment by indeyets** [comment]
Sure, I'd be glad to include Portfile.

anyway, syck is not under active development. If someone provides a bugfix — I apply that, but not more than that. syck is a YAML 1.0 parser and is quite dated.

Newer library is Libyaml, which supports 1.1

**Comment by apinstein** [comment]
Oh, very interesting, I wasn't aware that there was another active yaml lib. I will see if I can get that working (macports has libyaml, but no php5-yaml, though there is a pecl yaml-beta). So I will see -- if I can get that to work I'll just abandon this.

It would be really helpful if you put a note at the top of the README of your project that pointed to libyaml so that people finding it know that they should consider libyaml as a replacement.

**Comment by ryandesign** [comment]
This can probably be closed. php-yaml was added to MacPorts in 2012. Adding an "official Portfile" for php-syck to your repository is probably not useful; the canonical Portfile should probably be located in the MacPorts repository where it is now. If changes to this Portfile are needed, please file a ticket in the MacPorts issue tracker.
